import Image from "next/image";
import Link from "next/link";
import { Download } from "lucide-react";
import { Breadcrumbs } from "@/components/ui/breadcrumbs";
import { WallpaperGrid } from "./wallpaper-grid";
import { formatBytes } from "@/lib/utils";
import type { Wallpaper, Category, Tag, WallpaperAsset } from "@prisma/client";
type Detail = Wallpaper & { categories: { category: Category }[]; tags: { tag: Tag }[]; assets: WallpaperAsset[] };
type Card = Wallpaper & { categories: { category: Category }[]; tags: { tag: Tag }[] };
export function WallpaperDetail({ wallpaper, related }: { wallpaper: Detail; related: Card[] }) { const category = wallpaper.categories[0]?.category; return <div className="container-page py-7"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Wallpapers", href: "/wallpapers/latest" }, ...(category ? [{ label: category.name, href: `/categories/${category.slug}` }] : []), { label: wallpaper.title }]}/><div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_22rem]"><div><h1 className="text-3xl font-black sm:text-4xl">{wallpaper.title}</h1><p className="mt-3 max-w-2xl text-muted">{wallpaper.description}</p><div className="relative mt-6 aspect-[9/16] max-h-[78vh] overflow-hidden rounded-2xl border border-line bg-black"><Image src={wallpaper.imageUrl} alt={wallpaper.altText} fill priority sizes="(max-width: 1024px) 100vw, 70vw" className="object-contain"/></div></div><aside className="surface h-fit p-5"><a href={`/api/download/${wallpaper.slug}`} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-brand px-4 font-bold text-black"><Download size={19}/>Download original</a><dl className="mt-6 space-y-3 text-sm"><div className="flex justify-between gap-3"><dt className="text-muted">Resolution</dt><dd>{wallpaper.width} × {wallpaper.height}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted">File type</dt><dd>{wallpaper.mimeType.replace("image/", "").toUpperCase()}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted">Size</dt><dd>{formatBytes(wallpaper.fileSize)}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted">Category</dt><dd>{category ? <Link className="text-brand" href={`/categories/${category.slug}`}>{category.name}</Link> : "—"}</dd></div></dl>{wallpaper.tags.length > 0 && <div className="mt-6 border-t pt-5"><h2 className="font-bold">Tags</h2><div className="mt-3 flex flex-wrap gap-2">{wallpaper.tags.map(({ tag }) => <Link className="rounded-full border px-3 py-1 text-xs text-muted hover:text-white" href={`/search?q=${encodeURIComponent(tag.name)}`} key={tag.id}>{tag.name}</Link>)}</div></div>}</aside></div><section className="mt-14"><h2 className="text-2xl font-black">Related wallpapers</h2><div className="mt-5"><WallpaperGrid wallpapers={related}/></div></section>{category && <section className="mt-10 surface p-6"><h2 className="text-xl font-black">More {category.name} wallpapers</h2><p className="mt-2 text-muted">Explore a focused collection of {category.name.toLowerCase()} backgrounds for mobile.</p><Link className="mt-4 inline-block font-bold text-brand" href={`/categories/${category.slug}`}>Browse {category.name} →</Link></section>}</div>; }
