import { notFound } from "next/navigation";
import { Pagination } from "@/components/ui/pagination";
import { WallpaperGrid } from "@/components/wallpapers/wallpaper-grid";
import { getWallpaper, listWallpapers, relatedWallpapers } from "@/features/wallpapers/queries";
import { breadcrumbJsonLd, metadata, wallpaperJsonLd } from "@/lib/seo";
import { toTitle } from "@/lib/utils";
import { WallpaperDetail } from "@/components/wallpapers/wallpaper-detail";
const kinds = ["latest", "popular", "4k", "hd", "amoled", "trending"] as const;
export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ kind: string }> }) { const { kind } = await params; if (kinds.includes(kind as typeof kinds[number])) return metadata({ title: `${toTitle(kind)} Mobile Wallpapers`, description: `Browse ${kind} phone wallpapers for iPhone and Android.`, path: `/wallpapers/${kind}` }); const wallpaper = await getWallpaper(kind); return wallpaper ? metadata({ title: wallpaper.title, description: wallpaper.description.slice(0, 155), path: `/wallpapers/${wallpaper.slug}`, image: wallpaper.imageUrl }) : {}; }
export default async function ListingPage({ params, searchParams }: { params: Promise<{ kind: string }>; searchParams: Promise<{ page?: string }> }) { const { kind } = await params; if (!kinds.includes(kind as typeof kinds[number])) { const wallpaper = await getWallpaper(kind); if (!wallpaper) notFound(); const related = await relatedWallpapers(wallpaper.id, wallpaper.categories.map((item) => item.categoryId)); const jsonLd = [wallpaperJsonLd(wallpaper), breadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "Wallpapers", path: "/wallpapers/latest" }, { name: wallpaper.title, path: `/wallpapers/${wallpaper.slug}` }])]; return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}/><WallpaperDetail wallpaper={wallpaper} related={related}/></>; } const { page: pageValue } = await searchParams; const page = Math.max(1, Number(pageValue) || 1); const data = await listWallpapers({ kind: kind as typeof kinds[number], page }); return <div className="container-page py-10"><p className="eyebrow">Wallpaper library</p><h1 className="mt-2 text-3xl font-black">{toTitle(kind)} wallpapers</h1><p className="mt-3 text-muted">Curated phone wallpapers, optimized for sharp displays.</p><div className="mt-8"><WallpaperGrid wallpapers={data.items}/><Pagination page={page} pages={data.pages} path={`/wallpapers/${kind}`}/></div></div>; }
