import Link from "next/link";
import { SearchForm } from "@/components/search/search-form";
import { WallpaperGrid } from "@/components/wallpapers/wallpaper-grid";
import { getCategories } from "@/features/categories/queries";
import { listWallpapers } from "@/features/wallpapers/queries";
export const revalidate = 300;
export const dynamic = "force-dynamic";
function Section({ title, href, children }: { title: string; href: string; children: React.ReactNode }) { return <section className="container-page mt-14"><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow">Discover</p><h2 className="mt-1 text-2xl font-black">{title}</h2></div><Link href={href} className="text-sm font-semibold text-brand">View all</Link></div>{children}</section>; }
export default async function HomePage() { const [trending, latest, fourK, amoled, iphone, android, categories] = await Promise.all([listWallpapers({ kind: "trending", take: 8 }), listWallpapers({ kind: "latest", take: 8 }), listWallpapers({ kind: "4k", take: 4 }), listWallpapers({ kind: "amoled", take: 4 }), listWallpapers({ kind: "iphone", take: 4 }), listWallpapers({ kind: "android", take: 4 }), getCategories()]); return <><section className="container-page pt-14 sm:pt-20"><p className="eyebrow">Wallpapers for every screen</p><h1 className="mt-3 max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">Mobile Wallpapers</h1><p className="mt-4 max-w-xl text-base leading-7 text-muted">A fast, hand-picked library of exceptional 4K and HD wallpapers for iPhone and Android.</p><div className="mt-7"><SearchForm hero/></div><div className="mt-7 flex flex-wrap gap-2">{categories.slice(0, 8).map((category) => <Link className="rounded-full border border-line px-4 py-2 text-sm hover:border-brand" key={category.id} href={`/categories/${category.slug}`}>{category.name}</Link>)}</div></section><Section title="Trending now" href="/wallpapers/trending"><WallpaperGrid wallpapers={trending.items}/></Section><Section title="Latest wallpapers" href="/wallpapers/latest"><WallpaperGrid wallpapers={latest.items}/></Section><Section title="4K wallpapers" href="/wallpapers/4k"><WallpaperGrid wallpapers={fourK.items}/></Section><Section title="AMOLED wallpapers" href="/wallpapers/amoled"><WallpaperGrid wallpapers={amoled.items}/></Section><Section title="iPhone wallpapers" href="/iphone-wallpapers"><WallpaperGrid wallpapers={iphone.items}/></Section><Section title="Android wallpapers" href="/android-wallpapers"><WallpaperGrid wallpapers={android.items}/></Section><section className="container-page mt-14 grid gap-5 lg:grid-cols-2"><div className="surface p-6"><p className="eyebrow">Made for phones</p><h2 className="mt-2 text-2xl font-black">Find a screen that feels like yours.</h2><p className="mt-3 leading-7 text-muted">Explore original phone wallpaper in sharp formats, practical sizes, and clean categories. Every wallpaper page includes its resolution and a direct download.</p></div><div className="surface p-6"><p className="eyebrow">Frequently asked</p><h2 className="mt-2 font-bold">Are these wallpapers free?</h2><p className="mt-2 text-sm leading-6 text-muted">Wallpapers are free for personal use. Check the individual source and our terms before commercial use.</p><h2 className="mt-4 font-bold">Will they work on my device?</h2><p className="mt-2 text-sm leading-6 text-muted">Choose a high-resolution image and crop it in your device wallpaper settings for the best fit.</p></div></section></>; }
